name: Check Python format style

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  submodule-sync:
    uses: 3rdparty/dev-tools/.github/workflows/check-format-style.yml@main
    with:
      devtools_directory: submodules/dev-tools
