name: Run pre-merge checks
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  run-tests:
    name: Run pre-merge checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reboot-dev/pyprotoc-plugin
        uses: actions/checkout@v2
      - name: Run tests
        run: bazel test //...
