name: Run pre-merge checks
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  run-tests:
    name: Run pre-merge checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reboot-dev/pyprotoc-plugin
        uses: actions/checkout@v2
      - name: Install Python 3.9 and set it as default one
        run: |
          sudo apt update
          sudo apt install python3.9
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
          python --version
      - name: Run tests
        run: |
          python --version
          bazel test //...
